### ISSUE TITLE
Link has gone dead

### ISSUE THREAD

**Issue by domenic** [esdiscuss/esdiscuss.org#102]
https://esdiscuss.org/topic/relationship-between-globals-realms-and-global-env now just returns "Cannot GET /topic/relationship-between-globals-realms-and-global-env" :(

**Comment by ForbesLindesay** [comment]
It looks like the correct link is: https://esdiscuss.org/topic/relationship-between-globals-realms-and-global-environment-records

I don't know where the first list came from/why it's changed.

**Comment by ForbesLindesay** [comment]
Closing as I don't have enough information to try and fix this.
