### ISSUE TITLE
How to subscribe? 

### ISSUE THREAD

**Issue by kevinSuttle** [esdiscuss/esdiscuss.org#139]
I can't seem to find any way to be able to subscribe and register my email address. 
The bounced email doesn't help:

<img width="416" alt="screen shot 2016-07-26 at 12 50 59 pm" src="https://cloud.githubusercontent.com/assets/95672/17147204/c26ddc9c-532f-11e6-93ea-e1edb7c40304.png">

**Comment by ForbesLindesay** [comment]
Follow the big subscribe button on the home page: https://esdiscuss.org

I recommend lurking for a few weeks to get a feel for how other people present ideas before posting.

**Comment by kevinSuttle** [comment]
_Facepalm_
