### ISSUE TITLE
Add Google custom search?

### ISSUE THREAD

**Issue by olalonde** [esdiscuss/esdiscuss.org#179]
Would be helpful to have a google custom search form to search through the discussions.

**Comment by karlhorky** [comment]
I guess this is partially finished now with the Algolia search (screenshot below) but it would be nice to have a separate page for this.

![Screen Shot 2019-09-23 at 16 03 19](https://user-images.githubusercontent.com/1935696/65432995-7d0d8780-de1c-11e9-9f8e-ed4a0b45b291.png)

**Comment by ForbesLindesay** [comment]
Closing in favour of #42
