### ISSUE TITLE
JS on notes page is wrongly replacing initialisms with full names

### ISSUE THREAD

**Issue by ljharb** [esdiscuss/esdiscuss.org#229]
From https://esdiscuss.org/topic/oddities-in-2017-07-25-meeting-notes:

See https://esdiscuss.org/notes/2017-07-25 as compared to https://github.com/rwaldron/tc39-notes/blob/master/es8/2017-07/jul-25.md#10ii-vision-thing.

Looks like it's replacing "JS" with "Jaswanth Sreeram", "API" with "Andrew Paprocki", etc.

Perhaps https://github.com/esdiscuss/esdiscuss.org/blob/a90069cc327469c886876e88d24e5072ed8677ef/lib/process.js#L39-L84?

**Comment by bathos** [comment]
I think it may be [here](https://github.com/esdiscuss/esdiscuss.org/blob/a90069cc327469c886876e88d24e5072ed8677ef/lib/process.js#L118-L127) specifically.

**Comment by ljharb** [comment]
Fixed with #230, thanks!
