### ISSUE TITLE
Proposal: Array.prototype.forEachRight

### ISSUE THREAD

**Issue by AlastairTaft** [esdiscuss/esdiscuss.org#241]
This is a proposal for the `forEachRight` method for iterating over an array in reverse. Its pretty useful when you want to remove items from an array while iterating over it.

There exists both `reduce()` and `reduceRight()` so why not `forEach()` and `forEachRight()`?

I've created [a polyfill here](https://github.com/AlastairTaft/Array.prototype.forEachRight).

**Comment by ljharb** [comment]
Please read https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md for how to contribute; this repo is just for the esdiscuss website.

Separately, none of the other array methods have Right variants besides reduce; if we added another we'd want to add it for all of them, for consistency.

**Comment by AlastairTaft** [comment]
I had a pull request ready for that repo but the  contributing guidelines
say propose a topic on the ESDiscuss website. I couldn't see a way to do
that so I created an issue here because the only option on the website is
"Fork me". Then the read me here says "If you want a new feature
implemented, open a pull request or submit an issue."

I also tried to create an account on the Royalty Free Task Group but it
didn't seem to do anything.

I don't think you'd need to add it to all variants for consistency because
it doesn't change the current status quo which is being not consistent.
I.e. we have reduce and reduceRight but no methodRight for everything else.
It would make sense to add the methodRight variation where there is useful
use case

**Comment by ljharb** [comment]
esdiscuss is an email list; its suggesting you email the list (there's no facility for non-members to propose anything on github). Perhaps those docs need to be made clearer.

In general, having one exception is acceptable, two is a problem pattern.
