### ISSUE TITLE
Promised functions

### ISSUE THREAD

**Issue by lffg** [esdiscuss/esdiscuss.org#269]
<small><em>One new proposal for EcmaScript.</em></small>

# `Promised Functions`

Like `async/await`, the promised functions would be preceded by a keyword. In the case, `promised`, it would change the default behavior of the function, making it behave as a promise.

I will use as an example a classic `sleep` function:

```javascript
function sleep(forHowLong) {
  return new Promise((resolve, reject) => {
    setTimeout(function() {
      resolve();

      /**
       * For reject:
       * 
       * reject(Error('Some error'));
       */
    }, forHowLong);
  });
}
``` 

I think to avoid the huge amount of callbacks, there should be a syntax similar to this:

```javascript
promised function sleep(forHowLong) {
  setTimeout(function() {
    this.resolve(); // could even create a keyword like "resolve"

    /**
     * For reject:
     * 
     * this.reject(Error('Some error'));
     */
  }, forHowLong);
}
```

Note that the hypothetical keyword "promised" before the function statement makes it act as a promise.

Just a crazy idea I had. :)

**Comment by ljharb** [comment]
This sounds like something you should email to the lista - this repo is for managing the website for the list, not for individual proposals or general discussion.

**Comment by ljharb** [comment]
Instead of filing this as an issue, email it to the list as detailed [here](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal), and then you can close this issue.

**Comment by lffg** [comment]
So I need to send a email to this?
[es-discuss@mozilla.org](mailto://es-discuss@mozilla.org)

**Comment by ljharb** [comment]
Yep

**Comment by lffg** [comment]
I've tried, but I received this error:
```
Messages from non-subscribers are automatically rejected. Please
subscribe to the list first before attempting to post, or ensure that
you are posting using the address you subscribed with.
```
What is this list?

**Comment by ljharb** [comment]
Subscribe to the list fiesta - the document i linked you to sends you to the website for this repo (esdiscuss.org) which should have instructions.

**Comment by lffg** [comment]
[Thanks a lot.](https://esdiscuss.org/topic/ecmascript-proposal-promised-functions)
