### ISSUE TITLE
Implement as much as possible in pure HTML+CSS

### ISSUE THREAD

**Issue by KOLANICH** [esdiscuss/esdiscuss.org#283]
Enabling JavaScript is a security and privacy risk.

**Comment by ljharb** [comment]
That's simply not true or tenable; while it's great to minimize JavaScript usage, this is an exceedingly poor motivator for it.

**Comment by KOLANICH** [comment]
>That's simply not true

It is true. With JavaScript disabled attack surface is greatly reduced.

**Comment by ljharb** [comment]
Sure, with your computer turned off the attack surface is even more reduced. In practice, though, nobody does that, so it's a pretty useless paranoia-mode to optimize for.

**Comment by KOLANICH** [comment]
>In practice, though, nobody does that, so it's a pretty useless paranoia-mode to optimize for.

paranoia-mode in modern world is always useful.

**Comment by ForbesLindesay** [comment]
No paranoia is not helping you here. All these issues are pretty unhelpful and ill-thought out, but this one in particular is poor. This site **already** implements most things without JavaScript. You can use almost every aspect of the site without JavaScript, other than a few small interactions.

@ljharb Thanks for fielding these issues so patiently.
