### ISSUE TITLE
Stop using Google Analytics

### ISSUE THREAD

**Issue by KOLANICH** [esdiscuss/esdiscuss.org#284]
It's tracking, and tracking is unacceptable.

**Comment by ljharb** [comment]
Why? Tracking is not unacceptable; you can set your browser to "Do Not Track" if you don't want tracking.

**Comment by KOLANICH** [comment]
>Tracking is not unacceptable

Tracking is **completely** unacceptable.

**Comment by ljharb** [comment]
You'll have to elaborate; most of the internet doesn't believe this to be the case.

**Comment by KOLANICH** [comment]
>You'll have to elaborate; most of the internet doesn't believe this to be the case.

Most of Internet trusts NSA and tolerates trackers, most of DPRK votes for Kim Jong-un. I don't care what the most of Internet users think. The issue not about internet users, it's about the website, about the decisions its developers made and about who the ones who have made such decisions are.

**Comment by ljharb** [comment]
And the decisions they made are the current ones. You can certainly make your own website with your own decisions.

**Comment by KOLANICH** [comment]
>And the decisions they made are the current ones.

Good luck with these decisions. Bue.
