### ISSUE TITLE
Using Cloudflare or any other centralised CDN/antiDDoS is a privacy risk

### ISSUE THREAD

**Issue by KOLANICH** [esdiscuss/esdiscuss.org#285]

**Comment by ljharb** [comment]
What privacy concerns do you have?

Visiting any website is a "privacy risk" because you're giving some information to that server. If you trust the website you're visiting, you are also trusting its decision process about what to delegate that to. If you don't trust it, don't visit it.

**Comment by KOLANICH** [comment]
>If you trust the website you're visiting, you are also trusting its decision process about what to delegate that to. If you don't trust it, don't visit it.

Cloudflare doesn't worth htis trust. And trust must be minimised.
