### ISSUE TITLE
[meta] Why es-discuss uses mailing lists instead of GitHub issues?

### ISSUE THREAD

**Issue by NeekSandhu** [esdiscuss/esdiscuss.org#288]
Pretty sure the pros are pretty obvious but regardless, here's what I think makes GH issues a better discussion platform:

- Simple, centralized (Web interface driven instead of email <-> email)
- Emojis 👍 - 👎 to show support for proposals (original posts)
- Labels for much better management and search

**Comment by ForbesLindesay** [comment]
You won't get a response to that kind of issue here. This is just for maintaining the website and most of the people who actually use the mailing list aren't following issues here.

**Comment by ForbesLindesay** [comment]
P.S. adding emoji voting and labels to threads on esdiscuss.org would be cool :)
