### ISSUE TITLE
How to engage with esdiscuss

### ISSUE THREAD

**Issue by ericandrewlewis** [esdiscuss/esdiscuss.org#291]
Hi there,

I'm just joining the list now, and had to google around a bit to figure out how to.

I suggest a page be added that describes how to join and participate in the list.

**Comment by ForbesLindesay** [comment]
We have a pretty large "Subscribe" button on the home page (https://esdiscuss.org/). I don't know if we need more than that?

**Comment by ericandrewlewis** [comment]
Yeah...Looking back on this now I'm not sure what my suggestion was...closing out. Thanks for taking a look.
