### ISSUE TITLE
Internal Server Error when submitting an edit

### ISSUE THREAD

**Issue by UltCombo** [esdiscuss/esdiscuss.org#83]
I'm trying to edit [my post](https://esdiscuss.org/topic/array-prototype-values-is-not-web-compat-even-with-unscopables#content-3), but I'm getting an "Internal Server Error" whenever I submit the edit.

Any ideas?

I'd like to put "web-compatible." inside of the block quote, and remove the auto-generated quote in the end of the post.

**Comment by monolithed** [comment]
I've the same problem periodically
