### ISSUE TITLE
Searching for topics based on topic names or content

### ISSUE THREAD

**Issue by caitp** [esdiscuss/esdiscuss.org#85]
I'm often finding myself going through the "cmd+f, cmd+g, next" pattern for 20+ pages trying to find all discussion on particular topics. It would be great to have search faculties built into the application, to make t/his easier and mitigate the risk of RSI!

I might have a go at building it myself in a few weeks if nobody else cares to

**Comment by yukulele** [comment]
:+1:

**Comment by yukulele** [comment]
you can use google:
https://google.com/search?q=site:esdiscuss.org/topic/%20rest%20parameter
https://encrypted.google.com/search?q=site:esdiscuss.org/topic/%20intitle:%22rest%20parameter%22

**Comment by Delapouite** [comment]
Yes, this could be implemented as a Google Custom Search Integration https://developers.google.com/custom-search/ in the header of the website

**Comment by karlhorky** [comment]
Yeah a full-featured search (with separate page) would be a nice feature!

The current Algolia search box (seen below) is a good start but is limited and doesn't work on mobile:

![Screen Shot 2019-09-23 at 16 03 19](https://user-images.githubusercontent.com/1935696/65433161-cf4ea880-de1c-11e9-8b6c-a39030178d4e.png)

**Comment by ForbesLindesay** [comment]
Closing in favour of #42
