### ISSUE TITLE
Do we have to request moderator to edit our posts?

### ISSUE THREAD

**Issue by sirisian** [esdiscuss/esdiscuss.org#90]
I made a post earlier: https://esdiscuss.org/topic/es8-proposal-optional-static-typing But when I viewed it on esdiscuss.org I noticed I needed to use markdown. Editing just says server error. Was trying to replace it with this: http://pastebin.com/Pj0jah14

**Comment by ForbesLindesay** [comment]
Sorry about this (and my very slow response).  Currently you have to be a moderator to make changes to anybody's messages (even your own).  That is being fixed (see #94) so that people will be able to edit their own messages.
