### ISSUE TITLE
import statement alias properties

### ISSUE THREAD

**Issue by gajus** [esdiscuss/esdiscuss.org#91]
The current supported [import statement syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import):

```js
import name from "module-name";
import { member } from "module-name";
import { member as alias } from "module-name";
import { member1 , member2 } from "module-name";
import { member1 , member2 as alias2 , [...] } from "module-name";
import name , { member [ , [...] ] } from "module-name";
import "module-name";
```

It is missing an ability to alias the imported properties, e.g.

```js
import {
    map,
    filter
} as _ from 'lodash';
```

This should in effect create an object `_` with properties `map` and `filter`, i.e. it is equivalent to (except for the loose `map` and `filter`):

```js
import {
    map,
    filter
} from 'lodash';

let _ = {
    map,
    filter
};
```

The closest we have got at the moment is:

```js
import {
    map as lodashMap,
    filter as lodashFilter
    // or _map, _filter
} from 'lodash';
```

which is not ideal.

**Comment by gajus** [comment]
The purpose for having this syntax is to encourage a method of writing a code that enables dead code elimination, e.g.

Dead code elimination cannot be performed on the following code because of the dynamic nature of `_` invocation.

```js
import _ from 'lodash';

ajaxMethodToGetRandomLodashFunctionName((name) => {
    _[name]();
});
```

However, code elimination is possible when import statement is explicit, e.g.

```js
import {
    map,
    filter
} from 'lodash';

// ajaxMethodToGetRandomLodashFunctionName is not possible beyond map and filter.
```

The disadvantage of the above approach at the moment is scope pollution (`map` and `filter` are orphan).

This can be easily address by introducing object alias, e.g. 

```js
import {
    map,
    filter
} as _ from 'lodash';

// ajaxMethodToGetRandomLodashFunctionName is not possible beyond _.map and _.filter.
```

**Comment by domenic** [comment]
This doesn't appear to refer to a bug on the esdiscuss.org site. Probably filed in the wrong place.

**Comment by caitp** [comment]
You could have suggested they post a thread on esdiscuss to talk about it, since that's what everyone else is using esdiscuss for

**Comment by gajus** [comment]
It is really not clear how to use this website.

Do I need to email the contents of this github issue to es-discuss@mozilla.org?

**Comment by ForbesLindesay** [comment]
Yes.  You should subscribe to the mailing list at https://mail.mozilla.org/listinfo/es-discuss then send an email to that address.
